whisker:
  auth:
    endpoint: https://autopets.sso.iothings.site/oauth/token
    clientId: IYXzWN908psOm7sNpe4G.ios.whisker.robots
    clientSecret: C63CLXOmwNaqLTB2xXo6QIWGwwBamcPuaul
    early-refresh-minutes: 59
    credentials:
      username: ${LITTER_ROBOT_USER}
      password: ${LITTER_ROBOT_PASSWORD}
  api:
    key: p7ndMoj61npRZP5CVz9v4Uj0bG769xy6758QRBPb
    default: https://v2.api.whisker.iothings.site
    endpointPaths:
      users: /users
      robots: /users/{userId}/robots
      robot: /users/{userId}/robots/{robotId}
      activity: /users/{userId}/robots/{robotId}/activity?limit={limit}
      insights: /users/{userId}/robots/{robotId}/insights?days={days}
