whisker:
  auth:
    endpoint: https://autopets.sso.iothings.site/oauth/token
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    early-refresh-minutes: 5
    credentials:
      username: ${LITTER_ROBOT_USER}
      password: ${LITTER_ROBOT_PASSWORD}
  api:
    key: ${API_KEY}
    default: https://v2.api.whisker.iothings.site
    endpointPaths:
      users: /users
      robots: /users/{userId}/robots
      robot: /users/{userId}/robots/{robotId}
      activity: /users/{userId}/robots/{robotId}/activity?limit={limit}
      insights: /users/{userId}/robots/{robotId}/insights?days={days}
